---
- name: Compile, test and install nginx configuration
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_directory }}/nginx.conf"
    validate: nginx -t -c %s
  notify: Reload nginx

- name: Update logrotate
  template:
    src: logrotate.nginx.j2
    dest: /etc/logrotate.d/nginx
